# Generated by Django 3.2.8 on 2021-10-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='U_Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=100)),
                ('config_value', models.CharField(max_length=100)),
                ('config_type', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('APP', 'APP'), ('USER', 'USER')], default='APP', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='u_user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
