# Generated by Django 3.2.8 on 2021-10-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20211030_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='u_config',
            options={'verbose_name': 'U_Config'},
        ),
        migrations.AlterModelOptions(
            name='u_user_profile',
            options={'verbose_name': 'U_User_Profile'},
        ),
        migrations.AlterField(
            model_name='u_config',
            name='config_name',
            field=models.CharField(max_length=100, verbose_name='Config Name'),
        ),
        migrations.AlterField(
            model_name='u_config',
            name='config_type',
            field=models.CharField(max_length=100, verbose_name='Config Type'),
        ),
        migrations.AlterField(
            model_name='u_config',
            name='config_value',
            field=models.CharField(max_length=100, verbose_name='Config Value'),
        ),
        migrations.AlterField(
            model_name='u_user_profile',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='user_directory_path'),
        ),
    ]
