# Generated by Django 3.2.8 on 2021-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20211030_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_user_profile',
            name='first_name',
            field=models.CharField(default='Firstname', max_length=25),
        ),
        migrations.AlterField(
            model_name='u_user_profile',
            name='last_name',
            field=models.CharField(default='Lastname', max_length=25),
        ),
    ]
