# Generated by Django 3.2.8 on 2021-10-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_u_user_profile_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
